
debug: false

logging:
  level:
    #root:info
  file: /Users/mac/springboot-prd.log

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql//localhost:3306/test
    data-username: root
    data-password: 1111

mall:
  config:
    name: 商城-prd
    description: 化妆品特卖网站
    hot-sales: 20
    show-advert: true
server:
  port: 80
